//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gentings.AspNetCore.RazorPages.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gentings.AspNetCore.RazorPages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天前 的本地化字符串。
        /// </summary>
        internal static string DaysBefore {
            get {
                return ResourceManager.GetString("DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string DropdownListTagHelper_SelectDefaultText {
            get {
                return ResourceManager.GetString("DropdownListTagHelper_SelectDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到枚举类型，需要设置Value值或者使用For指定枚举属性！ 的本地化字符串。
        /// </summary>
        internal static string EnumDropdownListTagHelper_TypeNotFound {
            get {
                return ResourceManager.GetString("EnumDropdownListTagHelper_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string EventType_Core {
            get {
                return ResourceManager.GetString("EventType_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileProvider不存在！ 的本地化字符串。
        /// </summary>
        internal static string FileProviderNotFound {
            get {
                return ResourceManager.GetString("FileProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        internal static string HoursBefore {
            get {
                return ResourceManager.GetString("HoursBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刚刚 的本地化字符串。
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏显示 的本地化字符串。
        /// </summary>
        internal static string Mozmd_FullScreen {
            get {
                return ResourceManager.GetString("Mozmd_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        internal static string Mozmd_ModePreview {
            get {
                return ResourceManager.GetString("Mozmd_ModePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Bold {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Code {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Header {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Image {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Italic {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Link {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Ol {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Quote {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Ul {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        internal static string MunitesBefore {
            get {
                return ResourceManager.GetString("MunitesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string PageTagHelper_LastPage {
            get {
                return ResourceManager.GetString("PageTagHelper_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string PageTagHelper_NextPage {
            get {
                return ResourceManager.GetString("PageTagHelper_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 的本地化字符串。
        /// </summary>
        internal static string PageTagHelper_NumberPage {
            get {
                return ResourceManager.GetString("PageTagHelper_NumberPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击刷新验证码 的本地化字符串。
        /// </summary>
        internal static string VerifierTagHelper_ClickRefresh {
            get {
                return ResourceManager.GetString("VerifierTagHelper_ClickRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        internal static string YearDateFormat {
            get {
                return ResourceManager.GetString("YearDateFormat", resourceCulture);
            }
        }
    }
}
