//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gentings.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gentings.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string Interval_Day {
            get {
                return ResourceManager.GetString("Interval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Day {
            get {
                return ResourceManager.GetString("Interval_Each_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每月 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Month {
            get {
                return ResourceManager.GetString("Interval_Each_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每年 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Year {
            get {
                return ResourceManager.GetString("Interval_Each_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误，必须为MM-dd HH:mm格式。 的本地化字符串。
        /// </summary>
        internal static string Interval_Format_Error {
            get {
                return ResourceManager.GetString("Interval_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Interval_Month {
            get {
                return ResourceManager.GetString("Interval_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Interval_Second {
            get {
                return ResourceManager.GetString("Interval_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每隔 的本地化字符串。
        /// </summary>
        internal static string Interval_Seconds {
            get {
                return ResourceManager.GetString("Interval_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string Interval_Year {
            get {
                return ResourceManager.GetString("Interval_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [服务]{0}执行错误：{1}。 的本地化字符串。
        /// </summary>
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台任务进程 的本地化字符串。
        /// </summary>
        internal static string TaskHostedService {
            get {
                return ResourceManager.GetString("TaskHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于执行后台任务定时服务，后台单独线程监听定时任务操作 的本地化字符串。
        /// </summary>
        internal static string TaskHostedService_Description {
            get {
                return ResourceManager.GetString("TaskHostedService_Description", resourceCulture);
            }
        }
    }
}
