//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gentings.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gentings.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 你已经对比过一次新对象，不能重复对比变更对象！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Differed {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Differed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原有对象已经初始化，不能重复调用初始化方法！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Initialized {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象变更原始对象未初始化，请在修改对象时候先调用Init方法。 的本地化字符串。
        /// </summary>
        internal static string Differ_Uninitialized {
            get {
                return ResourceManager.GetString("Differ_Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Add {
            get {
                return ResourceManager.GetString("DifferAction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_AddFormat {
            get {
                return ResourceManager.GetString("DifferAction_AddFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Modify {
            get {
                return ResourceManager.GetString("DifferAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”由”{1}“修改为“{2}” 的本地化字符串。
        /// </summary>
        internal static string DifferAction_ModifyFormat {
            get {
                return ResourceManager.GetString("DifferAction_ModifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Remove {
            get {
                return ResourceManager.GetString("DifferAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_RemoveFormat {
            get {
                return ResourceManager.GetString("DifferAction_RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功发送 的本地化字符串。
        /// </summary>
        internal static string EmailStatus_Completed {
            get {
                return ResourceManager.GetString("EmailStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        internal static string EmailStatus_Failured {
            get {
                return ResourceManager.GetString("EmailStatus_Failured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待发送 的本地化字符串。
        /// </summary>
        internal static string EmailStatus_Pending {
            get {
                return ResourceManager.GetString("EmailStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件发送服务 的本地化字符串。
        /// </summary>
        internal static string EmailTaskService {
            get {
                return ResourceManager.GetString("EmailTaskService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送队列在数据库中的电子邮件 的本地化字符串。
        /// </summary>
        internal static string EmailTaskService_Description {
            get {
                return ResourceManager.GetString("EmailTaskService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件消息未设置！ 的本地化字符串。
        /// </summary>
        internal static string EventMessage_NullMessage {
            get {
                return ResourceManager.GetString("EventMessage_NullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件消息的用户Id未设置，并且当前用户还未登录！ 的本地化字符串。
        /// </summary>
        internal static string EventMessage_NullUserId {
            get {
                return ResourceManager.GetString("EventMessage_NullUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string EventType_Core {
            get {
                return ResourceManager.GetString("EventType_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统通知清理服务 的本地化字符串。
        /// </summary>
        internal static string NotificationTaskService {
            get {
                return ResourceManager.GetString("NotificationTaskService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理每个用户得系统通知，删除多余得系统通知 的本地化字符串。
        /// </summary>
        internal static string NotificationTaskService_Description {
            get {
                return ResourceManager.GetString("NotificationTaskService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存了“{0}”配置信息 的本地化字符串。
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置失败 的本地化字符串。
        /// </summary>
        internal static string SaveSettingsFailured {
            get {
                return ResourceManager.GetString("SaveSettingsFailured", resourceCulture);
            }
        }
    }
}
