//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gentings.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gentings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string AlertBlock_Caution {
            get {
                return ResourceManager.GetString("AlertBlock_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要 的本地化字符串。
        /// </summary>
        internal static string AlertBlock_Important {
            get {
                return ResourceManager.GetString("AlertBlock_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释 的本地化字符串。
        /// </summary>
        internal static string AlertBlock_Note {
            get {
                return ResourceManager.GetString("AlertBlock_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string AlertBlock_Tip {
            get {
                return ResourceManager.GetString("AlertBlock_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意 的本地化字符串。
        /// </summary>
        internal static string AlertBlock_Warning {
            get {
                return ResourceManager.GetString("AlertBlock_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能在服务内部设置 IsStack 和 Interval 属性！ 的本地化字符串。
        /// </summary>
        internal static string Argument_CannotSetIsStackAndInterval {
            get {
                return ResourceManager.GetString("Argument_CannotSetIsStackAndInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;不能为空。 的本地化字符串。
        /// </summary>
        internal static string Check_ArgumentIsEmpty {
            get {
                return ResourceManager.GetString("Check_ArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{1}&apos;的&apos;{0}&apos;属性不能为空。 的本地化字符串。
        /// </summary>
        internal static string Check_ArgumentPropertyNull {
            get {
                return ResourceManager.GetString("Check_ArgumentPropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;集合最少需要包含一个值。 的本地化字符串。
        /// </summary>
        internal static string Check_CollectionArgumentIsEmpty {
            get {
                return ResourceManager.GetString("Check_CollectionArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{1}”的属性“{0}”必须包含get访问器。 的本地化字符串。
        /// </summary>
        internal static string ClrPropertyGetterFactory_NoGetter {
            get {
                return ResourceManager.GetString("ClrPropertyGetterFactory_NoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{1}”的属性“{0}”必须包含set访问器。 的本地化字符串。
        /// </summary>
        internal static string ClrPropertySetterFactory_NoSetter {
            get {
                return ResourceManager.GetString("ClrPropertySetterFactory_NoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数值必须以“{0}”结尾！ 的本地化字符串。
        /// </summary>
        internal static string CommandArgs_Read_MustEndsWith {
            get {
                return ResourceManager.GetString("CommandArgs_Read_MustEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序即将在“{0}”秒后关闭... 的本地化字符串。
        /// </summary>
        internal static string CommandConsole_CloseAsync_DelayClose {
            get {
                return ResourceManager.GetString("CommandConsole_CloseAsync_DelayClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭! 的本地化字符串。
        /// </summary>
        internal static string CommandConsole_DelayAsync_Close {
            get {
                return ResourceManager.GetString("CommandConsole_DelayAsync_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化应用程序！  的本地化字符串。
        /// </summary>
        internal static string CommandConsole_StartAsync_Initailize {
            get {
                return ResourceManager.GetString("CommandConsole_StartAsync_Initailize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经成功启动了应用程序，可以输入命令进行手动操作！ 的本地化字符串。
        /// </summary>
        internal static string CommandConsole_StartAsync_SuccessStart {
            get {
                return ResourceManager.GetString("CommandConsole_StartAsync_SuccessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持命令“{0}”，请使用.help命令来获取帮助信息！ 的本地化字符串。
        /// </summary>
        internal static string CommandConsole_StartAsync_UseHelp {
            get {
                return ResourceManager.GetString("CommandConsole_StartAsync_UseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序可以使用的命令包含以下内容： 的本地化字符串。
        /// </summary>
        internal static string CommandHandlerFactory_CommandList {
            get {
                return ResourceManager.GetString("CommandHandlerFactory_CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示帮助信息 的本地化字符串。
        /// </summary>
        internal static string CommandHandlerFactory_ExecuteAsync_HelpDescription {
            get {
                return ResourceManager.GetString("CommandHandlerFactory_ExecuteAsync_HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持命令：.{0}，请使用.help命令查看可用命令 的本地化字符串。
        /// </summary>
        internal static string CommandHandlerFactory_ExecuteAsync_NotSupported {
            get {
                return ResourceManager.GetString("CommandHandlerFactory_ExecuteAsync_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出应用程序 的本地化字符串。
        /// </summary>
        internal static string CommandHandlerFactory_ExecuteAsync_Quit {
            get {
                return ResourceManager.GetString("CommandHandlerFactory_ExecuteAsync_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功添加了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Created {
            get {
                return ResourceManager.GetString("DataAction_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，添加“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_CreatedFailured {
            get {
                return ResourceManager.GetString("DataAction_CreatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功删除了所选择的{0}。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Deleted {
            get {
                return ResourceManager.GetString("DataAction_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailured {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了，因为包含的子项不为空。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailuredItemsNotEmpty {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailuredItemsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，“{0}”已经存在，操作失败。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Duplicate {
            get {
                return ResourceManager.GetString("DataAction_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功完成了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Success {
            get {
                return ResourceManager.GetString("DataAction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，发生了未知错误，操作失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UnknownError {
            get {
                return ResourceManager.GetString("DataAction_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功更新了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Updated {
            get {
                return ResourceManager.GetString("DataAction_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，更新“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UpdatedFailured {
            get {
                return ResourceManager.GetString("DataAction_UpdatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [数据库]执行SQL错误： 的本地化字符串。
        /// </summary>
        internal static string Database_SqlExecuteError {
            get {
                return ResourceManager.GetString("Database_SqlExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库迁移完成。 的本地化字符串。
        /// </summary>
        internal static string DataMigration_Completed {
            get {
                return ResourceManager.GetString("DataMigration_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库迁移错误（请查看日志文件）： 的本地化字符串。
        /// </summary>
        internal static string DataMigration_Error {
            get {
                return ResourceManager.GetString("DataMigration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库迁移失败。 的本地化字符串。
        /// </summary>
        internal static string DataMigration_Failured {
            get {
                return ResourceManager.GetString("DataMigration_Failured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始数据库迁移。 的本地化字符串。
        /// </summary>
        internal static string DataMigration_Start {
            get {
                return ResourceManager.GetString("DataMigration_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加了 的本地化字符串。
        /// </summary>
        internal static string DataResult_Created {
            get {
                return ResourceManager.GetString("DataResult_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除了 的本地化字符串。
        /// </summary>
        internal static string DataResult_Deleted {
            get {
                return ResourceManager.GetString("DataResult_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新了 的本地化字符串。
        /// </summary>
        internal static string DataResult_Updated {
            get {
                return ResourceManager.GetString("DataResult_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭调试信息显示！ 的本地化字符串。
        /// </summary>
        internal static string DebugCommandHandler_ExecuteAsync_DebugOff {
            get {
                return ResourceManager.GetString("DebugCommandHandler_ExecuteAsync_DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启调试信息显示！ 的本地化字符串。
        /// </summary>
        internal static string DebugCommandHandler_ExecuteAsync_DebugOn {
            get {
                return ResourceManager.GetString("DebugCommandHandler_ExecuteAsync_DebugOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示调试信息，如果关闭使用命令.debug off 的本地化字符串。
        /// </summary>
        internal static string DebugCommandHandler_Help_DebugOff {
            get {
                return ResourceManager.GetString("DebugCommandHandler_Help_DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经对比过一次新对象，不能重复对比变更对象！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Differed {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Differed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原有对象已经初始化，不能重复调用初始化方法！ 的本地化字符串。
        /// </summary>
        internal static string Differ_Duplicated_Initialized {
            get {
                return ResourceManager.GetString("Differ_Duplicated_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象变更原始对象未初始化，请在修改对象时候先调用Init方法。 的本地化字符串。
        /// </summary>
        internal static string Differ_Uninitialized {
            get {
                return ResourceManager.GetString("Differ_Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Add {
            get {
                return ResourceManager.GetString("DifferAction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_AddFormat {
            get {
                return ResourceManager.GetString("DifferAction_AddFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Modify {
            get {
                return ResourceManager.GetString("DifferAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”由”{1}“修改为“{2}” 的本地化字符串。
        /// </summary>
        internal static string DifferAction_ModifyFormat {
            get {
                return ResourceManager.GetString("DifferAction_ModifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除了 的本地化字符串。
        /// </summary>
        internal static string DifferAction_Remove {
            get {
                return ResourceManager.GetString("DifferAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string DifferAction_RemoveFormat {
            get {
                return ResourceManager.GetString("DifferAction_RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误：{0}。 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_InvalidParameters {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_Success {
            get {
                return ResourceManager.GetString("ErrorCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生未知错误 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_UnknownError {
            get {
                return ResourceManager.GetString("ErrorCode_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_ValidError {
            get {
                return ResourceManager.GetString("ErrorCode_ValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string EventLevel_Error {
            get {
                return ResourceManager.GetString("EventLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string EventLevel_Information {
            get {
                return ResourceManager.GetString("EventLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string EventLevel_Success {
            get {
                return ResourceManager.GetString("EventLevel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string EventLevel_Warning {
            get {
                return ResourceManager.GetString("EventLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性表达式&apos;{0}&apos;不正确， 表达式必须提供一种属性访问，如： &apos;t =&gt; t.MyProperty&apos;；如果式多个属性，需要如下代码表示：&apos;t =&gt; new {{ t.MyProperty1, t.MyProperty2 }}&apos;。 的本地化字符串。
        /// </summary>
        internal static string ExpressionExtensions_InvalidPropertiesExpression {
            get {
                return ResourceManager.GetString("ExpressionExtensions_InvalidPropertiesExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性表达式&apos;{0}&apos;不正确， 表达式必须提供一种属性访问，如： &apos;t =&gt; t.MyProperty&apos;。 的本地化字符串。
        /// </summary>
        internal static string ExpressionExtensions_InvalidPropertyExpression {
            get {
                return ResourceManager.GetString("ExpressionExtensions_InvalidPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有达到预期的字节。 的本地化字符串。
        /// </summary>
        internal static string FileHelper_InvalidByte {
            get {
                return ResourceManager.GetString("FileHelper_InvalidByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日报表 的本地化字符串。
        /// </summary>
        internal static string IndexedMode_Day {
            get {
                return ResourceManager.GetString("IndexedMode_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string IndexedMode_Hour {
            get {
                return ResourceManager.GetString("IndexedMode_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月报表 的本地化字符串。
        /// </summary>
        internal static string IndexedMode_Month {
            get {
                return ResourceManager.GetString("IndexedMode_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年报表 的本地化字符串。
        /// </summary>
        internal static string IndexedMode_Year {
            get {
                return ResourceManager.GetString("IndexedMode_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序初始进程 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService {
            get {
                return ResourceManager.GetString("InitializerHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序执行开始时执行的后台服务，数据库初始化等操作 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService_Description {
            get {
                return ResourceManager.GetString("InitializerHostedService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站初始化失败！ 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService_InitializedFailured {
            get {
                return ResourceManager.GetString("InitializerHostedService_InitializedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动网站完成。 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService_Started {
            get {
                return ResourceManager.GetString("InitializerHostedService_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动网站失败。 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService_StartFailured {
            get {
                return ResourceManager.GetString("InitializerHostedService_StartFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动网站... 的本地化字符串。
        /// </summary>
        internal static string InitializerHostedService_Starting {
            get {
                return ResourceManager.GetString("InitializerHostedService_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string Interval_Day {
            get {
                return ResourceManager.GetString("Interval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Day {
            get {
                return ResourceManager.GetString("Interval_Each_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每月 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Month {
            get {
                return ResourceManager.GetString("Interval_Each_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每年 的本地化字符串。
        /// </summary>
        internal static string Interval_Each_Year {
            get {
                return ResourceManager.GetString("Interval_Each_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误，必须为MM-dd HH:mm格式。 的本地化字符串。
        /// </summary>
        internal static string Interval_Format_Error {
            get {
                return ResourceManager.GetString("Interval_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Interval_Month {
            get {
                return ResourceManager.GetString("Interval_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Interval_Second {
            get {
                return ResourceManager.GetString("Interval_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每隔 的本地化字符串。
        /// </summary>
        internal static string Interval_Seconds {
            get {
                return ResourceManager.GetString("Interval_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string Interval_Year {
            get {
                return ResourceManager.GetString("Interval_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据迁移出错：{0}。 的本地化字符串。
        /// </summary>
        internal static string MigrationError {
            get {
                return ResourceManager.GetString("MigrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在“{1}”找不到“{0}”的操作符。 的本地化字符串。
        /// </summary>
        internal static string MigrationsSqlGenerator_UnknownOperation {
            get {
                return ResourceManager.GetString("MigrationsSqlGenerator_UnknownOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string MigrationStatus_Completed {
            get {
                return ResourceManager.GetString("MigrationStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string MigrationStatus_Error {
            get {
                return ResourceManager.GetString("MigrationStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迁移中 的本地化字符串。
        /// </summary>
        internal static string MigrationStatus_Normal {
            get {
                return ResourceManager.GetString("MigrationStatus_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个类只能包含一个版本“TimestampAttribute”特性属性。 的本地化字符串。
        /// </summary>
        internal static string Property_RowVersionOnlyOnePropertyEachClass {
            get {
                return ResourceManager.GetString("Property_RowVersionOnlyOnePropertyEachClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “TimestampAttribute”特性属性的数据类型必须为byte[]。 的本地化字符串。
        /// </summary>
        internal static string Property_TypeMustBeBytes {
            get {
                return ResourceManager.GetString("Property_TypeMustBeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节大小必须能被 8 整除。 的本地化字符串。
        /// </summary>
        internal static string RandomNumberGenerator_SizeInvalid {
            get {
                return ResourceManager.GetString("RandomNumberGenerator_SizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过了索引长度。 的本地化字符串。
        /// </summary>
        internal static string SourceReader_OutOfIndex {
            get {
                return ResourceManager.GetString("SourceReader_OutOfIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始位置字符和‘{0}’不匹配！ 的本地化字符串。
        /// </summary>
        internal static string SourceReader_StartCharNotMatch {
            get {
                return ResourceManager.GetString("SourceReader_StartCharNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型&apos;{0}&apos;暂时还不支持。 的本地化字符串。
        /// </summary>
        internal static string SqlExpressionVisitor_UnsupportedType {
            get {
                return ResourceManager.GetString("SqlExpressionVisitor_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定期清理存储文件夹和临时文件夹中得空文件夹或无效文件等 的本地化字符串。
        /// </summary>
        internal static string StorageClearTaskExecutor_Description {
            get {
                return ResourceManager.GetString("StorageClearTaskExecutor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储文件夹清理服务 的本地化字符串。
        /// </summary>
        internal static string StorageClearTaskExecutor_Name {
            get {
                return ResourceManager.GetString("StorageClearTaskExecutor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能获取表单文件实例或者文件长度为0！ 的本地化字符串。
        /// </summary>
        internal static string StorageDirectory_FormFileInvalid {
            get {
                return ResourceManager.GetString("StorageDirectory_FormFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [服务]{0}执行错误：{1}。 的本地化字符串。
        /// </summary>
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台任务进程 的本地化字符串。
        /// </summary>
        internal static string TaskHostedService {
            get {
                return ResourceManager.GetString("TaskHostedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于执行后台任务定时服务，后台单独线程监听定时任务操作 的本地化字符串。
        /// </summary>
        internal static string TaskHostedService_Description {
            get {
                return ResourceManager.GetString("TaskHostedService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体“{0}”的主键{1}包含的不值一个属性！ 的本地化字符串。
        /// </summary>
        internal static string TypeExtensions_PrimaryKeyIsNotSingleField {
            get {
                return ResourceManager.GetString("TypeExtensions_PrimaryKeyIsNotSingleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UploadFileFailured {
            get {
                return ResourceManager.GetString("UploadFileFailured", resourceCulture);
            }
        }
    }
}
